# Generated by Django 3.0.6 on 2020-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200529_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='donetable',
            name='donetime',
            field=models.CharField(max_length=50, null=True),
            preserve_default=False,
        ),
    ]
